name: build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install build-essential perl libfile-slurp-perl libjson-xs-perl libwww-perl libmime-tools-perl libyaml-perl libdatetime-perl cpanminus && sudo cpanm Bytes::Random::Secure Crypt::JWT OIDC::Lite::Client::WebServer OIDC::Lite::Model::IDToken && perl Makefile.PL && make && make test
